auth_enabled: true

http_prefix:

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  grpc_server_min_time_between_pings: 10s
  grpc_server_ping_without_stream_allowed: true

memberlist:
  join_members: ['dns+loki-distributor:7946', 'dns+loki-ingester:7946', 'dns+loki-querier:7946']
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_port: 7946

ingester:
  lifecycler:
    join_after: 30s
    observe_period: 5s
    ring:
      replication_factor: 2
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 0
  chunk_block_size: 262144
  # chunk_target_size: 1.572864e+06
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal

# Only needed for global rate strategy
distributor:
 ring:
   kvstore:
     store: memberlist

compactor:
  working_directory: /loki/data/retention
  shared_store: aws
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

schema_config:
  configs:
    - from: 2020-10-24 
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  index_queries_cache_config:
    memcached_client:
      consistent_hash: true
      addresses: 'memcached-index:11211'
    memcached:
      batch_size: 100
      parallelism: 100
  aws:
    bucketnames: ${AWS_BUCKETNAME}
    endpoint: ${AWS_ENDPOINT}
    region: ${AWS_REGION}
    sse_encryption: true
    access_key_id: ${AWS_ACCESS_KEY_ID} 
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3
    index_gateway_client:
      server_address: loki-index-gateway:9095

limits_config:
  cardinality_limit: 200000
  max_streams_per_user: 100000
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h 
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_query_parallelism: 20
  max_query_series: 10000
  retention_period: 168h

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    memcached_client:
      consistent_hash: true
      addresses: 'memcached-chunks:11211'
    memcached:
      batch_size: 100
      parallelism: 100

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 30min intervals
  split_queries_by_interval: 30m
  parallelise_shardable_queries: true
  cache_results: true

  results_cache:
    cache:
      memcached_client:
        timeout: '500ms'
        consistent_hash: true
        addresses: 'memcached-query-frontend:11211'
        update_interval: '1m'
        max_idle_conns: 16

frontend_worker:
  frontend_address: loki-query-frontend:9095
  grpc_client_config:
    max_send_msg_size: 1.048576e+08
  parallelism: 3
        
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-gateway:3100

querier:
  query_ingesters_within: 2h
